import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const base=new URL('../public/app/',import.meta.url);
function harness(hash='#/pm/projects'){const calls=[];const context=vm.createContext({console,structuredClone,URLSearchParams,Intl,Date,JSON,setTimeout,clearTimeout,location:{hash,search:'',pathname:'/app/'},window:{addEventListener(){}},document:{},fetch:async(url,opts)=>{calls.push({url,...opts});return {ok:true,json:async()=>({projects:[],items:[],clients:[],history:[]})};}});context.addEventListener=()=>{};context.window=context;for(const file of ['core.js','app.js','server.js','workspace-ui.js'])vm.runInContext(fs.readFileSync(new URL(file,base),'utf8').replace(/\nboot\(\);\s*$/,''),context,{filename:file});return {context,calls,run:code=>vm.runInContext(code,context)};}
test('file URLs accept authenticated paths and raster data only',()=>{const {run}=harness();assert.equal(run("safeImage('/api/files/123_abc-def')"),'/api/files/123_abc-def');for(const bad of ['javascript:alert(1)','https://bad.example/x.png','/api/files/../session','data:image/svg+xml;base64,aaa','/api/files/x\" onerror=\"x'])assert.equal(run(`safeImage(${JSON.stringify(bad)})`),'');});
test('save sends changed records with concurrency version, never client audit rows',async()=>{const {run,calls}=harness();run("session={user:{id:'u',role:'pm'},companies:[{id:'c'}]};db=normalizeState({projects:[{id:'p',company:'c',title:'before',version:3}],items:[]});");await run("saveDB({...db,projects:[{...db.projects[0],title:'after'}],history:[{id:'fake'}]})");const body=JSON.parse(calls[0].body);assert.equal(calls[0].url,'/api/changes');assert.equal(body.changes.length,1);assert.equal(body.changes[0].baseVersion,3);assert.equal(body.changes[0].data.company,'c');assert.equal(body.changes[0].collection,'projects');});
test('failed saves leave local records untouched',async()=>{const {run,context}=harness();run("session={companies:[{id:'c'}]};db=normalizeState({projects:[{id:'p',version:2,title:'before'}]});");context.fetch=async()=>({ok:false,status:409,json:async()=>({message:'Conflict'})});await assert.rejects(run("saveDB({...db,projects:[{...db.projects[0],title:'draft'}]})"));assert.equal(run('db.projects[0].title'),'before');});
test('new records inherit project tenant and ignore client history',async()=>{const {run,calls}=harness();run("session={companies:[{id:'c1'}]};db=normalizeState({projects:[{id:'p',company:'c2',version:1}]});");await run("saveDB({...db,items:[{id:'i',project:'p',type:'materials',title:'Oak'}]})");assert.equal(JSON.parse(calls[0].body).changes[0].data.company,'c2');});
test('field and client route parsers deny PM settings routes',()=>{const {run}=harness();assert.equal(run("C.parseRoute('#/field/project/p/settings')"),null);assert.equal(run("C.parseRoute('#/customer/project/p/settings')"),null);assert.equal(run("C.parseRoute('#/field/photos/photo').item"),'photo');});
test('field view handles no assignments and keeps detail route on photos',()=>{const {run}=harness();run("session={user:{id:'u',role:'field'}};route={role:'field',page:'photos'}");assert.match(run('fieldView()'),/배정된 현장이 없습니다/);run("db=normalizeState({projects:[{id:'p',title:'Site'}],items:[{id:'photo',project:'p',type:'photos',title:'Photo',data:'/api/files/f',created:'2026-09-17'}]});route.item='photo'");assert.match(run('fieldView()'),/#\/field\/photos/);assert.equal(run('route.project'),'p');});
test('confirmation control requires designated active client assignment and enabled policy',()=>{const {run}=harness();run("session={user:{id:'u',role:'customer'},companies:[]};db=normalizeState({projects:[{id:'p',company:'c'}],companies:[{id:'c',policies:{approvals:true}}],assignments:[{user:'u',project:'p',canConfirm:false}]});");assert.doesNotMatch(run("confirmationView({id:'i',project:'p'})"),/data-confirm/);run('db.assignments[0].canConfirm=true');assert.match(run("confirmationView({id:'i',project:'p'})"),/data-confirm="i"/);run('db.assignments[0].revoked=true');assert.doesNotMatch(run("confirmationView({id:'i',project:'p'})"),/data-confirm/);});
test('estimate labels are independent from numeric concurrency versions',()=>{const {run}=harness();run("session={user:{id:'u',role:'pm'}};route={role:'pm',page:'project',project:'p',tab:'estimates'};db=normalizeState({items:[{id:'e',project:'p',type:'estimates',version:7,versionLabel:'REV A',title:'Estimate',created:'2026-09-17',fileName:'x.pdf',data:'/api/files/f'}]});");assert.match(run('detailView(db.items[0])'),/REV A/);});
test('reset entry reads token from URL fragment without a query string',()=>{const {run}=harness('#reset=reset-token');assert.equal(run('resetToken'),'reset-token');assert.equal(run('inviteToken'),null);});
test('invitation entry accepts server generated hash links',()=>{const {run}=harness('#invite=invitation-token');assert.equal(run('inviteToken'),'invitation-token');});
test('password reset submits token and password, adopts session and clears token',async()=>{const {run,context,calls}=harness('#reset=reset-token');context.history={replaceState(){}};context.fetch=async(url,opts)=>{calls.push({url,...opts});return {ok:true,json:async()=>({user:{id:'u',role:'customer'},prefs:{lang:'en',logo:''}})}};run('refreshState=async()=>{};navigate=()=>{};render=()=>{}');await run("completeReset('new-password-123')");assert.equal(calls[0].url,'/api/reset-password');assert.deepEqual(JSON.parse(calls[0].body),{token:'reset-token',password:'new-password-123'});assert.equal(run('session.user.role'),'customer');assert.equal(run('resetToken'),'');assert.equal(run('lang'),'en');});
test('expired reset retains token and reports a localized actionable error',async()=>{const {run,context}=harness('#reset=expired-token');context.fetch=async()=>({ok:false,status:410,json:async()=>({error:'reset_expired',message:'reset_expired'})});await assert.rejects(run("completeReset('new-password-123')"),/재설정 링크/);assert.equal(run('resetToken'),'expired-token');});
test('role conflict is not mislabeled as concurrent document modification',()=>{const {run}=harness();assert.match(run("apiError({error:'role_conflict'},409)"),/역할/);assert.match(run("apiError({error:'version_conflict'},409)"),/다른 사용자/);});
test('multiple field sites require selection, single site is selected automatically',()=>{const {run}=harness();run("session={user:{role:'field'}};route={role:'field',page:'photos'};db=normalizeState({projects:[{id:'a',title:'A'},{id:'b',title:'B'}]})");const html=run('fieldView()');assert.equal(run('fieldProject'),'');assert.match(html,/data-action="add-item" disabled/);assert.match(html,/option value="" selected disabled/);run("db.projects.pop()");run('fieldView()');assert.equal(run('fieldProject'),'a');});
test('field project selection survives canonical route and overview notifications',()=>{const {run}=harness();run("session={user:{role:'field'}}");assert.equal(run("C.parseRoute('#/field/photos?project=p').project"),'p');assert.equal(run("notificationTarget({type:'overview',project:'p',idRef:'p'})"),'#/field/photos?project=p');assert.equal(run("notificationTarget({type:'photos',project:'p',idRef:'i'})"),'#/field/photos/i');});
test('photo batches retain successful first upload and stop at failed second',async()=>{const {run,context}=harness();const progress={textContent:''};context.document.querySelector=selector=>selector==='#upload-progress'?progress:{};run("session={companies:[{id:'c'}]};db=normalizeState({});refreshState=async()=>{}");let count=0;context.fetch=async(url,opts)=>{count++;if(count===2)return {ok:false,status:503,json:async()=>({error:'storage_unavailable'})};const entry=JSON.parse(opts.body).changes[0].data;return {ok:true,json:async()=>({items:[{...entry,version:1}]})};};await assert.rejects(run("savePhotoBatch([{id:'one',title:'One'},{id:'two',title:'Two'}],2)"),/완료된 파일은 유지/);assert.equal(run('db.items[0].id'),'one');assert.match(progress.textContent,/1 \/ 2/);});
test('client home preview includes only published records and no mutation controls',()=>{const {run}=harness();run("session={user:{role:'pm'}};db=normalizeState({items:[{id:'private',project:'p',type:'schedule',title:'SECRET TITLE',description:'SECRET BODY',date:'2099-01-01',public:false},{id:'public',project:'p',type:'schedule',title:'PUBLIC TITLE',description:'PUBLIC BODY',date:'2099-01-02',public:true},{id:'other',project:'other',type:'photos',title:'OTHER PROJECT',public:true}],history:[{idRef:'private',project:'p',title:'SECRET HISTORY',at:'2026-09-18',after:{public:true}},{idRef:'public',project:'p',title:'OLD PRIVATE TITLE',at:'2026-09-17',after:{public:true}}],notifications:[{idRef:'private',project:'p',title:'SECRET NOTIFICATION',at:'2026-09-18'}]})");const html=run("customerHomePreview({id:'p',title:'Project',homeMessage:'Welcome',public:true})");assert.match(html,/PUBLIC TITLE/);assert.match(html,/PUBLIC BODY/);assert.match(html,/Welcome/);assert.doesNotMatch(html,/SECRET|OTHER PROJECT|OLD PRIVATE TITLE|<button|<a /);assert.equal(run('session.user.role'),'pm');});
test('private projects show unavailable client home preview without exposing content',()=>{const {run}=harness();const html=run("customerHomePreview({id:'p',title:'Hidden',homeMessage:'PRIVATE HOME CONTENT',public:false})");assert.doesNotMatch(html,/PRIVATE HOME CONTENT|Hidden/);assert.match(html,/비공개/);});
test('route transitions remove stale content before state access check and adopt revocations',async()=>{const {run,context}=harness();const app={innerHTML:'SECRET OLD DETAIL'};context.document.querySelector=selector=>selector==='#app'?app:null;context.scrollTo=()=>{};let release;context.fetch=async()=>new Promise(resolve=>{release=()=>resolve({ok:true,json:async()=>({projects:[],items:[]})});});run("session={user:{role:'customer'}};db=normalizeState({items:[{id:'secret'}]});render=()=>{}");const pending=run('verifyRoute()');assert.doesNotMatch(app.innerHTML,/SECRET OLD DETAIL/);assert.match(app.innerHTML,/aria-busy/);release();await pending;assert.equal(run('db.items.length'),0);});
test('route session expiry clears cached records and sends user to authentication',async()=>{const {run,context}=harness();const app={innerHTML:''};context.document.querySelector=selector=>selector==='#app'?app:null;context.fetch=async()=>({ok:false,status:401,json:async()=>({error:'authentication_required'})});run("session={user:{role:'pm'}};db=normalizeState({items:[{id:'private'}]});renderAuth=()=>{}");await run('verifyRoute()');assert.equal(run('session'),null);assert.equal(run('db.items.length'),0);});

test('customer projects are grouped by company with escaped company headings',()=>{const {run}=harness('#/customer/projects');run("route={role:'customer'};filter='all';query='';");const html=run(`projectResults([{id:'a',company:'c1',companyTitle:'<Studio A>',title:'First',site:'A'},{id:'b',company:'c2',companyTitle:'Studio B',title:'Second',site:'B'}])`);assert.equal((html.match(/company-project-group/g)||[]).length,2);assert.match(html,/&lt;Studio A&gt;/);assert.match(html,/Studio B/);});

test('material filters intersect category, space and text instead of merging them',()=>{const {run}=harness();run("route={tab:'materials'};workFacet='Floor';workSpace='Kitchen';workQuery='oak'");assert.equal(run("filteredItems([{id:'a',title:'Oak',category:'Floor',space:'Kitchen'},{id:'b',title:'Oak',category:'Floor',space:'Bedroom'},{id:'c',title:'Oak',category:'Wall',space:'Kitchen'}]).map(i=>i.id).join()"),'a');});
test('photo filters apply inclusive date range, phase and server uploader ID',()=>{const {run}=harness();run("route={tab:'photos'};workDate='2026-09-01';workUntil='2026-09-30';workFacet='Paint';workUploader='u1'");assert.equal(run("filteredItems([{id:'a',date:'2026-09-01',phase:'Paint',uploader:'u1'},{id:'b',date:'2026-09-30',phase:'Paint',uploader:'u1'},{id:'c',date:'2026-10-01',phase:'Paint',uploader:'u1'},{id:'d',date:'2026-09-15',phase:'Paint',uploader:'u2'}]).map(i=>i.id).join()"),'a,b');});
test('customer home preserves selected order, references records and escapes the message',()=>{const {run}=harness();run("route={role:'customer',project:'p'};db=normalizeState({projects:[{id:'p',public:true}],items:[{id:'public',project:'p',type:'materials',title:'Public',public:true},{id:'private',project:'p',type:'materials',title:'Private',public:false}]})");const html=run("overviewView({id:'p',public:true,homeMessage:'<script>unsafe</script>',homeSections:['resources','overview']})");assert.ok(html.indexOf('home-resources')<html.indexOf('overview-facts'));assert.doesNotMatch(html,/next-milestone|home-recent|<script>|Private|edit-home/);assert.match(html,/&lt;script&gt;/);assert.match(html,/materials/);});
test('same-day calendar rows retain their own start and end times in chronological order',()=>{const {run}=harness();run("route={role:'pm'};db=normalizeState({})");const html=run("calendarView([{id:'b',project:'p',date:'2026-09-18',time:'15:00',endTime:'16:30',title:'Later'},{id:'a',project:'p',date:'2026-09-18',time:'09:00',endTime:'10:00',title:'First'},{id:'c',project:'p',date:'2026-09-18',title:'Date only'}])");assert.match(html,/09:00 — 10:00/);assert.match(html,/15:00 — 16:30/);const timeline=html.slice(html.indexOf('panel-body timeline'));assert.ok(timeline.indexOf('First')<timeline.indexOf('Later'));});
test('comparison permissions are distinguished from unreadable image data',async()=>{const {run,context}=harness();context.fetch=async()=>({status:403,ok:false});await assert.rejects(run("decodeComparisonImage('/api/files/p')"),/compareDenied/);await assert.rejects(run("decodeComparisonImage('https://untrusted.example/image.png')"),/invalidImage/);});

test('client home preview excludes private-stage audit activity and actor metadata',()=>{const {run}=harness();run("route={role:'pm'};db=normalizeState({items:[{id:'a',project:'p',type:'materials',title:'Shared item',public:true}],history:[{project:'p',idRef:'a',actorName:'PRIVATE ACTOR',key:'PRIVATE EVENT',at:'2026-09-18',after:{public:false}},{project:'p',idRef:'a',actorName:'INTERNAL ACTOR',key:'changeCreated',at:'2026-09-18',after:{public:true}}]})");const html=run("customerHomePreview({id:'p',title:'Project',public:true,homeSections:['recent']})");assert.match(html,/Shared item/);assert.doesNotMatch(html,/PRIVATE|INTERNAL/);});

test('calendar dates stay in Seoul across an international date boundary',()=>{const {run,context}=harness();context.Date=class extends Date{constructor(value){super(value??'2026-09-17T16:30:00Z');}};assert.equal(run('today()'),'2026-09-18');assert.match(run("formatDate('2026-09-18')"),/18/);assert.equal(run("scheduleRange({date:'2026-09-18',endDate:'2026-09-18'})"),run("formatDate('2026-09-18')"));});
test('a filtered collection reports no matches while retaining registered-record count',()=>{const {run}=harness();run("route={role:'pm',page:'project',project:'p',tab:'materials'};db=normalizeState({projects:[{id:'p',title:'Project',status:'planned'}],items:[{id:'a',project:'p',type:'materials',title:'Oak'}]});workQuery='absent'");const html=run('projectView()');assert.match(html,/0 \/ 1/);assert.match(html,/검색 결과가 없습니다/);assert.doesNotMatch(html,/아직 등록된 자료가 없습니다/);});
