import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApplication} from '../server/app.mjs';
import sharp from 'sharp';

test('server authorization, transactional changes, invitations, versions and private files',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'interior-test-'));
 const app=await createApplication({dataDir:dir,port:0,origin:'http://127.0.0.1',test:true});
 const owner=await app.bootstrap({email:'pm@example.test',name:'PM',company:'Studio A',password:'TestPassword!2026'});
 const ownerB=await app.bootstrap({email:'other@example.test',name:'Other',company:'Studio B',password:'TestPassword!2026'});
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;
 async function request(path,{cookie='',body,method=body?'POST':'GET'}={}){const res=await fetch(base+path,{method,headers:{...(cookie?{cookie}:{}),...(body?{'Content-Type':'application/json',Origin:base}:{})},body:body?JSON.stringify(body):undefined});return {status:res.status,body:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};}
 try{
  await t.test('app canonical path and unversioned scripts are safe to refresh',async()=>{const redirect=await fetch(base+'/app?lang=en',{redirect:'manual'});assert.equal(redirect.status,302);assert.equal(redirect.headers.get('location'),'/app/?lang=en');const script=await fetch(base+'/app/server.js');assert.equal(script.status,200);assert.equal(script.headers.get('cache-control'),'no-cache');});
  await t.test('no anonymous state; login accepts valid secret only',async()=>{assert.equal((await request('/api/state')).status,401);assert.equal((await request('/api/login',{body:{email:'pm@example.test',password:'wrong'}})).status,401);});
  const login=await request('/api/login',{body:{email:'pm@example.test',password:'TestPassword!2026'}}),cookie=login.cookie;assert.equal(login.status,200);
  const other=(await request('/api/login',{body:{email:'other@example.test',password:'TestPassword!2026'}})).cookie;
  const project={id:'p1',title:'First',site:'Site',start:'2026-01-01',end:'2099-12-31',status:'planned',public:true,company:owner.company};
  const change=(collection,data,baseVersion=0)=>request('/api/changes',{cookie,body:{changes:[{collection,id:data.id,baseVersion,data}]}});
  await t.test('creation generates assignment and server audit',async()=>{const r=await change('projects',project);assert.equal(r.status,200);assert.equal(r.body.projects[0].version,1);assert.equal(r.body.assignments[0].user,owner.user);assert.equal(r.body.history.length,1);});
  await t.test('company isolation and unauthorized arbitrary IDs',async()=>{assert.equal((await request('/api/state',{cookie:other})).body.projects.length,0);assert.equal((await request('/api/changes',{cookie:other,body:{changes:[{collection:'projects',id:'p1',baseVersion:1,data:{...project,title:'Attack'}}]}})).status,403);});
  await t.test('stale version returns conflict without overwriting record',async()=>{assert.equal((await change('projects',{...project,title:'Updated'},1)).status,200);assert.equal((await change('projects',{...project,title:'Stale'},1)).status,409);assert.equal((await request('/api/state',{cookie})).body.projects[0].title,'Updated');});
  await t.test('pending invitation policy blocks until owner enables it',async()=>{assert.equal((await request('/api/invitations',{cookie,body:{company:owner.company,project:'p1',email:'client@example.test',role:'customer'}})).status,403);assert.equal((await request('/api/company',{cookie,method:'PUT',body:{id:owner.company,title:'Studio A',policies:{participants:true,approvals:true}}})).status,200);});
  const inv=await request('/api/invitations',{cookie,body:{company:owner.company,project:'p1',email:'client@example.test',role:'customer',from:'2020-01-01',until:'2099-12-31',canConfirm:true}});assert.equal(inv.status,201);
  const token=new URL(inv.body.url,base).hash.split('=')[1];
  const accepted=await request('/api/accept-invite',{body:{token,name:'Client',password:'ClientPassword!2026'}});assert.equal(accepted.status,200);const client=accepted.cookie;
  await t.test('invitation single use and client cannot create projects',async()=>{assert.equal((await request('/api/accept-invite',{body:{token,name:'Again',password:'ClientPassword!2026'}})).status,410);assert.equal((await request('/api/changes',{cookie:client,body:{changes:[{collection:'projects',id:'bad',baseVersion:0,data:{...project,id:'bad'}}]}})).status,403);});
  await change('items',{id:'m1',project:'p1',type:'materials',title:'Oak',public:false,spec:'A'});
  await t.test('client cannot see unpublished record or mutate it',async()=>{assert.equal((await request('/api/state',{cookie:client})).body.items.length,0);assert.equal((await request('/api/changes',{cookie:client,body:{changes:[{collection:'items',id:'m1',baseVersion:1,data:{id:'m1',project:'p1',type:'materials',title:'Attack',public:true}}]}})).status,403);});
  await change('items',{id:'m1',project:'p1',type:'materials',title:'Oak',public:true,spec:'A'},1);
  await t.test('confirmation snapshots server actor and invalidates after material revision',async()=>{const r=await request('/api/confirm',{cookie:client,body:{item:'m1',version:2}});assert.equal(r.status,200);assert.equal(r.body.items[0].confirmation.name,'Client');const version=(await request('/api/state',{cookie})).body.items[0].version;await change('items',{id:'m1',project:'p1',type:'materials',title:'Oak',public:true,spec:'B'},version);assert.equal((await request('/api/state',{cookie:client})).body.items[0].confirmation,null);});
  await t.test('private file checks current project access on every download',async()=>{const pdf='data:application/pdf;base64,'+Buffer.from('%PDF-1.4\n1 0 obj\n<<>>\nendobj\n%%EOF').toString('base64');const r=await change('items',{id:'e1',project:'p1',type:'estimates',title:'Estimate',public:false,versionLabel:'1',fileName:'estimate.pdf',data:pdf});assert.equal(r.status,200);const url=r.body.items.find(i=>i.id==='e1').data;assert.equal((await fetch(base+url,{headers:{cookie:other}})).status,403);assert.equal((await fetch(base+url,{headers:{cookie:client}})).status,403);assert.equal((await fetch(base+url,{headers:{cookie}})).status,200);});
  await t.test('batch failure rolls back earlier changes and audit',async()=>{const before=(await request('/api/state',{cookie})).body;const r=await request('/api/changes',{cookie,body:{changes:[{collection:'items',id:'m2',baseVersion:0,data:{id:'m2',project:'p1',type:'materials',title:'Temp'}},{collection:'items',id:'bad',baseVersion:0,data:{id:'bad',project:'missing',type:'materials',title:'Invalid'}}]}});assert.notEqual(r.status,200);const after=(await request('/api/state',{cookie})).body;assert.equal(after.items.length,before.items.length);assert.equal(after.history.length,before.history.length);});
  await t.test('request originals and client authored corrections are immutable',async()=>{const r=await request('/api/changes',{cookie:client,body:{changes:[{collection:'items',id:'r1',baseVersion:0,data:{id:'r1',project:'p1',type:'requests',title:'Request',description:'Original',public:true}}]}});assert.equal(r.status,200);const old=r.body.items.find(i=>i.id==='r1');assert.equal((await request('/api/changes',{cookie:client,body:{changes:[{collection:'items',id:'r1',baseVersion:old.version,data:{...old,description:'Overwritten'}}]}})).status,403);});
  await t.test('public recent updates have no audit snapshots or private values',async()=>{const state=(await request('/api/state',{cookie:client})).body;assert.ok(state.history.length);assert.ok(state.history.every(h=>!('before'in h)&&!('after'in h)));assert.ok(!JSON.stringify(state).includes('"hash"'));});
  await t.test('archival preserves files and assigned PM can restore',async()=>{const state=(await request('/api/state',{cookie})).body,item=state.items.find(i=>i.id==='e1');assert.equal((await change('items',{...item,archived:true},item.version)).status,200);const archived=await request('/api/archives?project=p1',{cookie});assert.equal(archived.body.items.length,1);assert.equal((await request('/api/restore',{cookie:client,body:{id:item.id,version:item.version+1}})).status,403);assert.equal((await request('/api/restore',{cookie,body:{id:item.id,version:item.version+1}})).status,200);});
  await t.test('field upload is assignment scoped, uploader is server-owned, revoked download fails',async()=>{
   const invitation=await request('/api/invitations',{cookie,body:{company:owner.company,project:'p1',email:'field@example.test',role:'field',from:'2020-01-01',until:'2099-12-31'}});
   const fieldToken=new URL(invitation.body.url,base).hash.split('=')[1];const joined=await request('/api/accept-invite',{body:{token:fieldToken,name:'Field worker',password:'FieldPassword!2026'}});assert.equal(joined.status,200);const fc=joined.cookie;
   const png=await sharp({create:{width:2,height:2,channels:3,background:'#fa3600'}}).png().toBuffer();const item={id:'photo1',project:'p1',type:'photos',title:'Photo',fileName:'site.png',data:'data:image/png;base64,'+png.toString('base64'),phase:'Walls',date:'2026-09-17',public:true,uploader:'forged'};
   const saved=await request('/api/changes',{cookie:fc,body:{changes:[{collection:'items',id:item.id,baseVersion:0,data:item}]}});assert.equal(saved.status,200);const actual=saved.body.items.find(i=>i.id===item.id);assert.equal(actual.public,false);assert.equal(actual.uploader,joined.body.user.id);assert.ok(saved.body.items.every(i=>i.type==='photos'));
   const state=(await request('/api/state',{cookie})).body,assigned=state.assignments.find(a=>a.role==='field');await request('/api/assignments',{cookie,body:{...assigned,until:'2020-01-01'}});
   assert.equal((await request('/api/state',{cookie:fc})).body.projects.length,0);assert.equal((await fetch(base+actual.data,{headers:{cookie:fc}})).status,403);
  });
  await t.test('revoked assignment hides data and notification targets',async()=>{const state=(await request('/api/state',{cookie})).body;const ass=state.assignments.find(a=>a.role==='customer');assert.equal((await request('/api/assignments',{cookie,body:{...ass,revoked:true}})).status,200);assert.equal((await request('/api/state',{cookie:client})).body.projects.length,0);});
  await t.test('cross-origin write is blocked',async()=>{const r=await fetch(base+'/api/logout',{method:'POST',headers:{cookie,Origin:'https://evil.test','Content-Type':'application/json'},body:'{}'});assert.equal(r.status,403);});
 }finally{await new Promise(r=>app.server.close(r));await app.close();await rm(dir,{recursive:true,force:true});}
});
