import {createServer} from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,join,extname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {openRepository} from './repository.mjs';
import {uid,now,token,digest,fail,required,email,passwordHash,passwordValid,publicUser,manager,member,assignment,canProject,canItem,companiesFor,visibleState,audit} from './security.mjs';
import {storage,storeFile} from './files.mjs';
import {applyChanges} from './changes.mjs';
const PUBLIC=resolve(fileURLToPath(new URL('../public/',import.meta.url)));
const roles=['pm','customer','field'];
export function configuration(overrides={}){return {dataDir:resolve(process.env.DATA_DIR||'data'),port:Number(process.env.PORT||8766),host:process.env.HOST||'127.0.0.1',origin:process.env.APP_ORIGIN||'http://127.0.0.1:8766',production:process.env.NODE_ENV==='production',databaseUrl:process.env.DATABASE_URL||'',postgresSSL:process.env.POSTGRES_SSL==='true',postgresCA:process.env.POSTGRES_SSL_CA||'',supabaseURL:(process.env.SUPABASE_URL||'').replace(/\/$/,''),supabaseKey:process.env.SUPABASE_SERVICE_ROLE_KEY||'',supabaseBucket:process.env.SUPABASE_BUCKET||'interior-private',sessionDays:Number(process.env.SESSION_DAYS||7),maxFileBytes:Number(process.env.MAX_FILE_MB||20)*1024*1024,...overrides};}
export async function createApplication(options={}){
 const config=configuration(options);if(config.production){required(/^https:\/\//.test(config.origin),500,'https_origin_required');required(config.databaseUrl||process.env.ALLOW_SQLITE_PRODUCTION==='true',500,'production_database_required');}
 required(!config.supabaseURL||config.supabaseKey,500,'storage_key_required');
 const repo=await openRepository(config),driver=storage(config),rates=new Map();
 function rate(key,limit=20){const at=Date.now(),r=rates.get(key);if(!r||r.until<at){rates.set(key,{count:1,until:at+900000});}else{required(r.count<limit,429,'too_many_attempts');r.count++;}if(rates.size>10000)for(const[k,v]of rates)if(v.until<at)rates.delete(k);}
 async function bootstrap({email:address,name,company,password}){const mail=email(address),hash=await passwordHash(password);return repo.write(store=>{required(!store.list('users').some(u=>u.email===mail),409,'email_exists');required(name&&company,400,'required_fields');const user=uid(),cid=uid();store.put('users',{id:user,email:mail,name,role:'pm',hash,active:true});store.put('companies',{id:cid,title:company,policies:{participants:false,approvals:false},template:''});store.put('memberships',{id:uid(),company:cid,user,active:true,canManage:true});return {user,company:cid};});}
 function sessionToken(req){return /(?:^|;\s*)interior_session=([A-Za-z0-9_-]+)/.exec(req.headers.cookie||'')?.[1];}
 function actor(store,req){const s=store.get('sessions',digest(sessionToken(req)||''));if(!s||s.expiresAt<now())return null;const u=store.get('users',s.user);return u?.active?u:null;}
 function sessionInfo(store,user){return user?{user:publicUser(user),prefs:store.get('preferences',user.id)||{lang:'ko',logo:''},companies:companiesFor(store,user)}:{user:null};}
 function newSession(store,user,res){const value=token(),days=config.sessionDays;store.put('sessions',{id:digest(value),user:user.id,expiresAt:new Date(Date.now()+days*86400000).toISOString()});res.setHeader('Set-Cookie',`interior_session=${value}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${Math.floor(days*86400)}${config.production?'; Secure':''}`);return sessionInfo(store,user);}
 function endSession(store,req,res){store.remove('sessions',digest(sessionToken(req)||''));res.setHeader('Set-Cookie',`interior_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0${config.production?'; Secure':''}`);}
 function accessibleInvite(store,value){const inv=store.get('invitations',digest(value||''));required(inv&&!inv.used&&inv.expiresAt>now(),410,'invite_expired');return inv;}
 function validRange(body){for(const k of ['from','until'])if(body[k])required(/^\d{4}-\d{2}-\d{2}$/.test(body[k])&&!Number.isNaN(Date.parse(body[k])),400,'invalid_date');required(!body.from||!body.until||body.from<=body.until,400,'invalid_date');}
 function assignmentWrite(store,user,data){const {company,project}=data,p=store.get('projects',project),c=store.get('companies',company);required(manager(store,user,company)&&c?.policies.participants&&p?.company===company,403,'assignment_forbidden');const target=store.get('users',data.user);required(target&&member(store,target,company),400,'invalid_member');validRange(data);const old=store.list('assignments').find(a=>a.project===project&&a.user===data.user);const rec={id:old?.id||uid(),company,project,user:data.user,role:target.role,from:data.from||null,until:data.until||null,revoked:data.revoked===true,canConfirm:target.role==='customer'&&data.canConfirm===true};store.put('assignments',rec);const event={id:uid(),company,project,type:'overview',idRef:project,title:p.title,key:'changeEdited',at:now(),actor:user.id,actorName:user.name,before:old,after:rec};store.put('history',event);return rec;}
 async function jsonBody(req){required((req.headers['content-type']||'').startsWith('application/json'),415,'json_required');let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;required(size<=Math.max(30*1024*1024,config.maxFileBytes*1.5),413,'request_too_large');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{fail(400,'invalid_json');}}
 const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
 async function api(req,res,url){const path=url.pathname,method=req.method;
  if(path==='/api/health'&&method==='GET')return json(res,200,{ok:true,database:repo.backend});
  if(!['GET','HEAD'].includes(method)){const origin=req.headers.origin;const expected=config.test?'http://'+req.headers.host:config.origin;required(origin===expected,403,'origin_forbidden');required(req.headers['sec-fetch-site']!=='cross-site',403,'origin_forbidden');}
  const body=['POST','PUT','PATCH'].includes(method)?await jsonBody(req):{};
  if(path==='/api/session'&&method==='GET')return json(res,200,await repo.read(s=>sessionInfo(s,actor(s,req))));
  if(path==='/api/login'&&method==='POST'){rate('login-ip:'+req.socket.remoteAddress,100);const mail=email(body.email);rate('login:'+mail,20);const result=await repo.write(async s=>{const u=s.list('users').find(u=>u.email===mail&&u.active);const ok=await passwordValid(body.password,u?.hash);required(u&&ok,401,'invalid_credentials');return newSession(s,u,res);});return json(res,200,result);}
  if(path==='/api/logout'&&method==='POST'){await repo.write(s=>endSession(s,req,res));return json(res,200,{user:null});}
  if(path==='/api/invite'&&method==='GET'){rate('invite-ip:'+req.socket.remoteAddress,100);const value=url.searchParams.get('token');return json(res,200,await repo.read(s=>{const i=accessibleInvite(s,value);return {email:i.email,role:i.role,company:s.get('companies',i.company)?.title,expiresAt:i.expiresAt};}));}
  if(path==='/api/accept-invite'&&method==='POST'){rate('accept-ip:'+req.socket.remoteAddress,30);const result=await repo.write(async s=>{const i=accessibleInvite(s,body.token),company=s.get('companies',i.company);required(company?.policies.participants&&s.get('projects',i.project),403,'policy_pending');let u=s.list('users').find(u=>u.email===i.email);if(u){required(actor(s,req)?.id===u.id,401,'login_to_accept');required(u.role===i.role,409,'role_conflict');}else{required(typeof body.name==='string'&&body.name.trim().length&&body.name.length<=100,400,'name_required');u={id:uid(),name:body.name.trim(),email:i.email,role:i.role,hash:await passwordHash(body.password),active:true};s.put('users',u);}if(!member(s,u,i.company))s.put('memberships',{id:uid(),company:i.company,user:u.id,active:true,canManage:false});const assigner=s.get('users',i.invitedBy);required(assigner&&manager(s,assigner,i.company),403,'invite_revoked');assignmentWrite(s,assigner,{...i,user:u.id});i.used=now();s.put('invitations',i);return newSession(s,u,res);});return json(res,200,result);}
  if(path==='/api/reset-password'&&method==='POST'){rate('reset-ip:'+req.socket.remoteAddress,20);const result=await repo.write(async s=>{const reset=s.get('resets',digest(body.token||''));required(reset&&!reset.used&&reset.expiresAt>now(),410,'reset_expired');const u=s.get('users',reset.user);required(u?.active,403);u.hash=await passwordHash(body.password);s.put('users',u);reset.used=now();s.put('resets',reset);for(const ss of s.list('sessions').filter(x=>x.user===u.id))s.remove('sessions',ss.id);return newSession(s,u,res);});return json(res,200,result);}
  const user=await repo.read(s=>actor(s,req));required(user,401,'authentication_required');
  if(path==='/api/state'&&method==='GET')return json(res,200,await repo.read(s=>visibleState(s,user)));
  if(path==='/api/archives'&&method==='GET')return json(res,200,await repo.read(s=>{required(user.role==='pm',403,'forbidden');const project=url.searchParams.get('project');required(assignment(s,user,project),403,'forbidden');return {items:s.list('items').filter(i=>i.project===project&&i.archived)};}));
  if(path==='/api/restore'&&method==='POST')return json(res,200,await repo.write(s=>{required(user.role==='pm',403,'forbidden');const item=s.get('items',body.id);required(item?.archived&&assignment(s,user,item.project),403,'forbidden');required(item.version===Number(body.version),409,'version_conflict');const old=structuredClone(item);item.archived=false;item.version++;item.updated=now();s.put('items',item);audit(s,user,old,item,'items');return visibleState(s,user);}));
  if(path==='/api/export'&&method==='GET'){res.setHeader('Content-Disposition','attachment; filename="workspace-export.json"');return json(res,200,await repo.read(s=>({exportedAt:now(),...visibleState(s,user)})));}
  if(path==='/api/changes'&&method==='POST')return json(res,200,await repo.write(s=>{required(actor(s,req),401,'authentication_required');return applyChanges(s,user,body.changes,config,driver);}));
  if(path==='/api/preferences'&&method==='PUT'){const result=await repo.write(async s=>{const old=s.get('preferences',user.id)||{lang:'ko',logo:''};required(!body.lang||['ko','en'].includes(body.lang),400,'invalid_language');let logo=old.logo;if(body.logo!==undefined){logo=body.logo;if(logo)logo=await storeFile(s,logo,{parent:'profile:'+user.id,company:null,project:null,logo:true,image:true,name:'logo.png'},config,driver);}const prefs={id:user.id,lang:body.lang||old.lang,logo};s.put('preferences',prefs);return {prefs};});return json(res,200,result);}
  if(path==='/api/password'&&method==='POST'){rate('password:'+user.id,20);const result=await repo.write(async s=>{const u=s.get('users',user.id);required(await passwordValid(body.current,u.hash),401,'invalid_credentials');u.hash=await passwordHash(body.password);s.put('users',u);for(const ss of s.list('sessions').filter(x=>x.user===u.id))s.remove('sessions',ss.id);return newSession(s,u,res);});return json(res,200,result);}
  if(path==='/api/company'&&method==='PUT'){const result=await repo.write(s=>{required(manager(s,user,body.id),403,'company_forbidden');const c=s.get('companies',body.id);required(typeof body.title==='string'&&body.title.trim().length&&body.title.length<=200,400,'title_required');const before=structuredClone(c);c.title=body.title.trim();if(body.policies)c.policies={participants:body.policies.participants===true,approvals:body.policies.approvals===true};if(body.template!==undefined){required(typeof body.template==='string'&&body.template.length<=10000,400,'invalid_template');c.template=body.template;}s.put('companies',c);s.put('history',{id:uid(),company:c.id,project:null,type:'company',idRef:c.id,title:c.title,at:now(),actor:user.id,actorName:user.name,key:'changeEdited',before,after:c});return visibleState(s,user);});return json(res,200,result);}
  if(path==='/api/invitations'&&method==='POST'){const result=await repo.write(s=>{const c=s.get('companies',body.company),p=s.get('projects',body.project);required(manager(s,user,body.company)&&c?.policies.participants&&p?.company===body.company,403,'invitation_forbidden');required(roles.includes(body.role),400,'invalid_role');validRange(body);const value=token(),expiresAt=new Date(Date.now()+48*3600000).toISOString();s.put('invitations',{id:digest(value),company:body.company,project:body.project,email:email(body.email),role:body.role,from:body.from||null,until:body.until||null,canConfirm:body.canConfirm===true,invitedBy:user.id,expiresAt,used:null});return {url:config.origin+'/app/#invite='+value,expiresAt};});return json(res,201,result);}
  if(path==='/api/assignments'&&method==='POST')return json(res,200,await repo.write(s=>{assignmentWrite(s,user,body);return visibleState(s,user);}));
  if(path==='/api/confirm'&&method==='POST'){const result=await repo.write(s=>{const item=s.get('items',body.item);required(user.role==='customer'&&canItem(s,user,item)&&['materials','designs'].includes(item.type),403,'confirmation_forbidden');const a=assignment(s,user,item.project),company=s.get('companies',item.company);required(a?.canConfirm&&company?.policies.approvals,403,'confirmation_forbidden');required(item.version===Number(body.version),409,'version_conflict');const old=structuredClone(item);item.confirmation={by:user.id,name:user.name,at:now(),version:item.version};item.version++;item.updated=now();s.put('items',item);audit(s,user,old,item,'items');return visibleState(s,user);});return json(res,200,result);}
  if(path==='/api/notifications/read'&&method==='POST')return json(res,200,await repo.write(s=>{const n=s.get('notifications',body.id);required(n?.user===user.id,404,'not_found');n.read=true;s.put('notifications',n);return visibleState(s,user);}));
  if(path.startsWith('/api/files/')&&method==='GET'){
   const f=await repo.read(s=>{const f=s.get('files',path.split('/').pop());required(f,404,'not_found');const [kind,id]=f.parent.split(':');required(kind==='profile'?id===user.id:kind==='items'&&canItem(s,user,s.get('items',id)),403,'file_forbidden');return f;});
   const buffer=await driver.get(f.id);res.writeHead(200,{'Content-Type':f.mime,'Content-Length':buffer.length,'Cache-Control':'private, no-store','Content-Disposition':`${f.mime.startsWith('image/')||f.mime==='application/pdf'&&url.searchParams.get('preview')==='1'?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(f.name).replace(/'/g,'%27')}`,'Content-Security-Policy':"default-src 'none'; sandbox"});res.end(buffer);return;
  }
  fail(404,'not_found');
 }
 const server=createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');if(config.production)res.setHeader('Strict-Transport-Security','max-age=31536000');try{const url=new URL(req.url,'http://local');if(url.pathname.startsWith('/api/'))return await api(req,res,url);required(['GET','HEAD'].includes(req.method),405,'method_not_allowed');let pathname=decodeURIComponent(url.pathname);if(pathname==='/app'){res.writeHead(302,{Location:'/app/'+url.search,'Cache-Control':'no-store'});res.end();return;}if(pathname==='/')pathname='/index.html';if(pathname==='/app'||pathname==='/app/')pathname='/app/index.html';const file=resolve(PUBLIC,'.'+pathname);required(file.startsWith(PUBLIC+sep),404,'not_found');let info;try{info=await stat(file);}catch{fail(404,'not_found');}required(info.isFile(),404,'not_found');const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.wasm':'application/wasm','.avif':'image/avif','.ttf':'font/ttf','.pfb':'application/octet-stream','.svg':'image/svg+xml','.woff2':'font/woff2','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.json':'application/json'}[extname(file)]||'application/octet-stream';if(pathname.startsWith('/app/'))res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; worker-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data: blob:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self'; form-action 'self'");res.writeHead(200,{'Content-Type':mime,'Cache-Control':['.html','.js','.mjs','.css'].includes(extname(file))?'no-cache':'public, max-age=3600'});res.end(req.method==='HEAD'?undefined:await readFile(file));}catch(e){if(res.headersSent){res.end();return;}if(!e.status)console.error('request_failure',e.code||e.name);json(res,e.status||500,{error:e.code||'server_error',message:e.status?e.message:'Server error'});}});
 server.requestTimeout=120000;server.headersTimeout=15000;
 return {server,repo,driver,config,bootstrap,close:()=>repo.close()};
}

